baseURL = "https://www.martinpickering.com/"
languageCode = "en-gb"
title = "Martin Pickering"
theme = "diary"
copyright="Martin Pickering"
googleAnalytics = "UA-149508279-2"
enableEmoji=true
enableRobotsTXT=true
#pygmentsUseClasses=true
pygmentsCodeFences=true

paginate=20

[params.intro]
  main = "Hi, I'm Martin"
  sub = "I'm a Code Monkey, Beekeeper and Forester"

[taxonomies]
   tag = "tags"
   category = "categories"
#  design = "designs"
#  tech = "techs"

#[blackfriday]
#  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['posts'] # values: ['post', 'portfolio'] only accept one section, to be displayed below 404

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "images/martin-pickering.jpg" # - default "/images/devabee.jpg"
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  twitter = "https://twitter.com/devabees"
  linkedin = "https://www.linkedin.com/in/pickeringmartin"
  pencil = "mailto:mail@martinpickering.com"
#  github = "https://github.com/"
#  medium = "https://medium.com/"
#  codepen = "https://codepen.io/"
#  facebook = "https://www.facebook.com/"
#  youtube = "https://www.youtube.com/"
#  instagram = "https://www.instagram.com/"
#  gitlab = "https://gitlab.com/"
#  keybase = "https://keybase.io/"

[params.contact]
  email = ""
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

#[[menu.main]]
#  identifier = "about"
#  name = "About"
#  title = "About section"
#  url = "/about/"
#  weight = -120

#[[menu.main]]
#  identifier = "portfolio"
#  name = "Portfolio"
#  title = "Portfolio"
#  url = "/portfolio/"
#  weight = -110

[[menu.main]]
  name = "Archive"
  url = "/posts/"
  weight = 100

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 110

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 120

[[menu.main]]
  name = "About me"
  url = "/about/"
  weight = 130


[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false