name: Manual workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: jakejarvis/hugo-build-action@v0.92.0
#      with:
#        args: --minify
    - uses: actions/upload-artifact@v2
      with:
        name: website
        path: './public'
    - uses: anishathalye/proof-html@v1
      with:
        directory: './public'
        check_favicon: 'false'
        empty_alt_ignore: 'true'
        url_ignore: |
          https://naveocommerce.com/
          https://www.atlassian.com/git/tutorials/comparing-workflows#centralized-workflow
        url_ignore_re: |
          ^/__/firebase
          ^/404.html/page
          ^http://www.orkneyjar.com/history
          ^https://www.linkedin.com
